### ISSUE TITLE
CSS Implementation for Textboxes

### ISSUE THREAD

**Issue by atharvagadkari05** [DesignSystemsOSS/eccentrictouch#110]
This is a feature request v2.0 (Sprint 02). This project needs all possible CSS Properties and here we have a feature request to implement text boxes. We need to implement this feature as shown below.

![image](https://user-images.githubusercontent.com/74293435/113908640-64917200-97f4-11eb-8348-b1f86c374fc3.png)

- [x] Textboxes
- [x] Textareas

Refer to this document for detailed info.

Also, Let's work together, Join our discord server: https://discord.gg/8JVG5rwW

**Comment by yashsehgal** [comment]
These features are being implemented with other form elements.

Please take a look at the issue (#144 ) - Form elements are not linked with the new CSS updates.

**Comment by yashsehgal** [comment]
The issue has been resolved at the docs site.
Please refer to the URL below, everything is working now.

Docs URL: https://designsystemsoss.github.io/eccentrictouch.docs/#/?id=introduction
