### ISSUE TITLE
[NEW FEATURES]: More input components CSS Implementation is required

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#115]
**Is your feature request related to a problem? Please describe.**
There are so many input features remaining as of now. Such as 
![image](https://user-images.githubusercontent.com/62352288/114311359-10e09a80-9b0c-11eb-8f56-f8e827d58fd9.png)
![image](https://user-images.githubusercontent.com/62352288/114311373-1c33c600-9b0c-11eb-895a-eaf0a5868b5d.png)
![image](https://user-images.githubusercontent.com/62352288/114311384-2655c480-9b0c-11eb-89a4-9cecd07d468d.png)

**Describe the solution you'd like**
Some of the input elements are modified and most of them are remaining.

**Comment by yashsehgal** [comment]
- [ ] Button
- [ ] Checkbox

**Comment by Jaspreet099** [comment]
- [ ] btn
- [ ] button
- [ ] checkbox
- [ ] color
- [ ] date
- [ ] datetime
- [ ] datetime-local
- [ ] email
- [ ] file
- [ ] hidden
- [ ] image
- [ ] month
- [ ] number
- [ ] password
- [ ] radio
- [ ] range
- [ ] reset
- [ ] search
- [ ] submit
- [ ] tel
- [ ] text
- [ ] time
- [ ] url
- [ ] week

**Comment by yashsehgal** [comment]
These are assigned to @yashsehgal 
![image](https://user-images.githubusercontent.com/62352288/114314785-c6661a80-9b19-11eb-9cfb-68e79b03229f.png)

**Comment by Jaspreet099** [comment]
these assigned to @Jaspreet099 
![image](https://user-images.githubusercontent.com/75212002/114314863-15ac4b00-9b1a-11eb-9de0-49be90912fe0.png)

**Comment by atharvagadkari05** [comment]
![image](https://user-images.githubusercontent.com/74293435/114314944-6fad1080-9b1a-11eb-9c3e-0597af8d2e3f.png)
