### ISSUE TITLE
Wrong version on the docs.

### ISSUE THREAD

**Issue by DevCassie** [DesignSystemsOSS/eccentrictouch#125]
**Describe the bug**
When you read on how to link eccentric to your webpage it says it's at version 1.0.

**To Reproduce**
1. Go to https://designsystemsoss.github.io/eccentrictouch.docs/#/?id=documentation-eccentric-touch-v20
2. Click on https://designsystemsoss.github.io/eccentrictouch.docs/#/?id=how-to-link 
3. See error

**Expected behavior**
I think the version should be 2.0 according to the CDN link.

**Screenshots**
![image](https://user-images.githubusercontent.com/19227530/114517078-44bbdd00-9c3e-11eb-85c8-cb531abdf25b.png)

**Comment by yashsehgal** [comment]
Thanks for raising this issue @DevCassie

**Comment by atharvagadkari05** [comment]
Issue #125 has been resolved by @atharvagadkari05.
I'm closing this issue.

**Comment by yashsehgal** [comment]
Alright @atharvagadkari05
