### ISSUE TITLE
[Component Implementation]: Header Component CSS/JS properties to be added

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#129]
**Is your feature request related to a problem? Please describe.**
We need to create a set of linked CSS Properties for our header component. Its implementation should be this easy that the user just has to create a header component using the header tag `<header>` and an options list using the `<li>` tag.

This would give the user a Header like this ⬇️ 
![image](https://user-images.githubusercontent.com/62352288/115017718-92517780-9ed4-11eb-901a-93d3635dd19b.png)
Ignore the logo, which can be added using the `float: left;` property whereas all the header options will be shifted to the right section using `float: right;`. 

Also, This header component will have a feature of self-modification using JS with CSS/SCSS, of course.
So that, The User doesn't have to create a separate header for responsiveness of the website. In fact, This header will automatically be converted to a Hamburger Menu.

This issue has 3 milestones:
- [x] Header Implementation for Desktop View
- [ ] Header Implementation for Mobile Views
- [ ] Tests for Header Component should be written

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by yashsehgal** [comment]
@harshita9621 @Sumit11081996 
Hey, folks 👋🏽 Sorry for the late response. 

This issue has been implemented but not explained in the docs. So, If you want to contribute to the documentation part, I can assign this to you both.

There will be 2 issues regarding this in the docs project
- Issue for explaining the feature implementation
- Adding media (Images, GIFs) related to the feature implementation (code reference for users)

Share your thoughts on this?
Good day :D
