### ISSUE TITLE
(JS-0125) Found the usage of undeclared variables

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#151]
## Description
Variable that are not defined but they are being used in the code. This would give a potential errors that may break the code. It might have happen due to mistype of the variable name. &lt;!--more--&gt; Potential ReferenceErrors may result from misspellings of variable and parameter names, or accidental implicit …

## Occurrences
There are 24 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/DesignSystemsOSS/eccentrictouch/issue/JS-0125/occurrences/](https://deepsource.io/gh/DesignSystemsOSS/eccentrictouch/issue/JS-0125/occurrences/)

**Comment by SHUBHANSHU-creator** [comment]
can u help me to get started with this issue, which js file has an undeclared variable?

**Comment by yashsehgal** [comment]
> can u help me to get started with this issue, which js file has an undeclared variable?

Hey @SHUBHANSHU-creator 👋🏽 
Actually, This is issue has been resolved as of now. We are about to close it :)
