### ISSUE TITLE
Need to create a complete Style Guide for the Eccentric Touch

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#157]
**Is your feature request related to a problem? Please describe.**
This is a component CSS Library and later It'll be having CSS Methods for basic & high-level components too. In Order to make the implementation easy for the users, we need to start working on a Styleguide for our project. Which will be containing things like Implementation, Usage, Variations, Adding external CSS Components into our components, Do's & Dont's, and Overall Best Practices.
The Styleguide will be implemented on the website and in a Markdown file also.

**Describe alternatives you've considered**
Try Looking to these websites/webpages for more reference.
- https://material.io/design
- https://material.io/components?platform=web

**Comment by harsh72835** [comment]
in this issue we have to design complete style guide ,right? like some documentation page which we have for bootstrap and material design page
