### ISSUE TITLE
(JS-0125) Found the usage of undeclared variables

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#182]
## Description
Variable that are not defined but they are being used in the code. This would give a potential errors that may break the code. It might have happen due to mistype of the variable name. &lt;!--more--&gt; Potential ReferenceErrors may result from misspellings of variable and parameter names, or accidental implicit …

## Occurrences
There are 12 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/DesignSystemsOSS/eccentrictouch/issue/JS-0125/occurrences/](https://deepsource.io/gh/DesignSystemsOSS/eccentrictouch/issue/JS-0125/occurrences/)

**Comment by ItsMeIshan** [comment]
hey, @yashsehgal I wanna know that is this issue same as for issue #151 ?
and can I work on this issue?

**Comment by yashsehgal** [comment]
> hey, @yashsehgal I wanna know that is this issue same as for issue #151 ?
> and can I work on this issue?

Yes @ItsMeIshan It's the same as #151 as it's an auto-generated issue.
And, Sure! You can get started with this.

**Comment by ItsMeIshan** [comment]
sure! @yashsehgal

**Comment by yashsehgal** [comment]
This issue has been resolved :)
