### ISSUE TITLE
[FEATURE]: Implementation of Progress Bars

### ISSUE THREAD

**Issue by Jaspreet099** [DesignSystemsOSS/eccentrictouch#211]
### Description
CSS for implementing progress bars is needed. The length of the progress with be operated by various classes defining various lengths for the progress bars.

### How to implement this feature
There will be 2 divisions, one inside another. The parent div will act as a complete bar and the internal div will be operated accordingly by using the width property in CSS.

This is a demo UI of how the progress bars will look like.
![image](https://user-images.githubusercontent.com/75212002/120837786-c7994e00-c584-11eb-9201-3d9b76288a5e.png)

**Comment by yashsehgal** [comment]
Thanks for raising this issue @Jaspreet099 But we have already implemented this feature.
Please refer to #172
