### ISSUE TITLE
[FEATURE]: Implementation of Accordion

### ISSUE THREAD

**Issue by Jaspreet099** [DesignSystemsOSS/eccentrictouch#212]
### Description
An accordion menu is a vertically stacked list of headers that can be clicked to reveal or hide content associated with them. 

### Implementation (Design)
![image](https://user-images.githubusercontent.com/75212002/120838870-efd57c80-c585-11eb-8447-0bc013354ca2.png)

**Comment by yashsehgal** [comment]
This issue is especially for LGMSoC Contributors.

**Comment by Aiswarika** [comment]
Can I work on this issue?

**Comment by yashsehgal** [comment]
Yes @Aiswarika 👍🏽 
You can get started with this issue. If you want to look for any reference for this, Go to this [Figma](https://www.figma.com/file/yqbBQK5NKqkzobrsSpj2T8/eccentrictouch2.0?node-id=0%3A1) file and you will be good to go!

Good Luck 💯

**Comment by Aiswarika** [comment]
Thank you! I will be working on it as a part of LGM SOC after the 10th.

**Comment by yashsehgal** [comment]
> Thank you! I will be working on it as a part of LGM SOC after the 10th.

Sure @Aiswarika No such issues in that :)

**Comment by atharvagadkari05** [comment]
Hey @Aiswarika, what's your status on this issue?
are you still working on this??
