### ISSUE TITLE
Scroll To Top button

### ISSUE THREAD

**Issue by Aiswarika** [DesignSystemsOSS/eccentrictouch#213]
I would like to add a scroll to the top button. Please assign me this issue.

**Comment by VaishnaviNigam25** [comment]
I want to work on this.Kindly assign me or let me know if someone else is working

**Comment by yashsehgal** [comment]
Hey @VaishnaviNigam25 👋🏽 
Thanks for raising this issue, we can work on that. Can you please elaborate on the implementation for the same?
Also, Before implementing this feature, you first need to design it in this [Figma file](https://www.figma.com/file/yqbBQK5NKqkzobrsSpj2T8/eccentrictouch2.0?node-id=0%3A1).

The design patterns are already listed there in the file, you can take a look at them. And feel free to hop into the [Discord Server](https://discord.gg/GpHBdA68fg) and discuss your doubts.

Good Luck!!

**Comment by yashsehgal** [comment]
Both of you can interact with each other and get this feature done :) 🚀

**Comment by harshita9621** [comment]
Hii,  I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by aktamoli0910** [comment]
Hi, I would like to work on this issue under LGM SOC'21. Thank you

**Comment by atharvagadkari05** [comment]
@harshita9621 @Sumit11081996 @aktamoli0910  You all can Join Discord as well as Slack for further discussion on this issue. 
As we have plenty of people on this issue, I think we can distribute some work and have you all on the board.

**Comment by 1anshu-56** [comment]
Please assign it to me I want to work on this issue as I have experience with this issue.

**Comment by coding-geek21** [comment]
I would like to work on this, I will complete within a day, please assign me @yashsehgal
