### ISSUE TITLE
To add automatic releases

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#214]
We are planning to add github-action that will automate the releasing process. 
This release will be having a properly defined description template.

**Comment by yashsehgal** [comment]
> @yashsehgal there is already a release action what else we need to add can you please explain.

Hey 👋🏽 
Actually, I tried implementing this but things were not working out. If you know what are the things breaking then I can assign you this task. 😃

**Comment by ItsMeIshan** [comment]
I am also learning Github actions but I can also try to implement it best!

**Comment by yashsehgal** [comment]
> I am also learning Github actions but I can also try to implement it best!

Sure, You can get started and if you have any issues/doubts feel free to discuss them here.

**Comment by ItsMeIshan** [comment]
that's awesome!

**Comment by ItsMeIshan** [comment]
hey @yashsehgal https://github.com/apps/vercel 
can you check it this would work for automatic deploys for PRs!
