### ISSUE TITLE
add color box using HEX colors 

### ISSUE THREAD

**Issue by Nicks-tech** [DesignSystemsOSS/eccentrictouch#215]
can  I work on this issue under LGM-SOC'21

**Comment by yashsehgal** [comment]
Hey @Nicks-tech 👋🏽 
Thanks for raising this issue. Could you please elaborate it more further or maybe start a discussion [here](https://github.com/DesignSystemsOSS/eccentrictouch/discussions) to discuss it with team members?

It's great to have you here 🚀

**Comment by Nicks-tech** [comment]
I will be adding different color boxes as given in figma

**Comment by yashsehgal** [comment]
No, those boxes are for color reference only. 
You're talking about these, correct me if I am wrong.
![image](https://user-images.githubusercontent.com/62352288/120988417-2d135780-c79c-11eb-9b36-2e54e24d0fb5.png)

**Comment by Nicks-tech** [comment]
oh sry,my bad I was not able  to understand it .Iam clossing this issue.

**Comment by yashsehgal** [comment]
No problem, Feel to ask other queries as well 😊
