### ISSUE TITLE
Adding more buttons

### ISSUE THREAD

**Issue by PranavChauhan22** [DesignSystemsOSS/eccentrictouch#220]
**Is your feature request related to a problem? Please describe.**
The site has four buttons and I want to add four more.

**Describe the solution you'd like**
Will add more more buttons and will reflect the same in docs

**Describe alternatives you've considered**
N/A

**Additional context**
-

Please assign me this issue under lgm-soc participant

**Comment by yashsehgal** [comment]
Hey @PranavChauhan22 👋🏽
What kind of buttons you want to add as this project follows a theme as well, so if you have any ideas then feel free to share them here. Maybe like a canvas file or something of your choice. 😃 
 
Thanks for raising this issue. 🚀

**Comment by Sejal2801** [comment]
Please assign it to me
