### ISSUE TITLE
Add a pointer cursor on the buttons

### ISSUE THREAD

**Issue by supzi-del** [DesignSystemsOSS/eccentrictouch#222]
**Is your feature request related to a problem? Please describe.**
When the pointer is hovered on the buttons on homepage, pointer should be cursor type.

**Comment by yashsehgal** [comment]
> **Is your feature request related to a problem? Please describe.**
> When the pointer is hovered on the buttons on homepage, pointer should be cursor type.

Sure, You can get started working on this issue. Feel free to ask your doubts as well.

**Comment by supzi-del** [comment]
I should work only on the test files, right?

**Comment by yashsehgal** [comment]
Yeah @supzi-del when you're doing changes in the CSS, you can test the `test` HTML files as well.
