### ISSUE TITLE
Add opacity effects in the buttons

### ISSUE THREAD

**Issue by vimalprogrammer** [DesignSystemsOSS/eccentrictouch#226]
Add opacity effects to the button demo's under the Buttons section in components. It will give the feeling of pressing the button.

Reference below...
![1_xWjw0QixSN1EW8wxCcTGTw](https://user-images.githubusercontent.com/76787061/121579031-f2821700-ca48-11eb-8481-0e8535f1e0c9.jpeg)

I would like to work on this issue under LGMSOC, please assign me...

**Comment by yashsehgal** [comment]
Thanks for raising this issue @vimalprogrammer 👋🏽 
We can surely work on this one. Also, could you please make these hover images for all kinds of buttons?

**Comment by 1anshu-56** [comment]
I want to work on this issue as I am familiar with this issue can you please assign it to me.

**Comment by atharvagadkari05** [comment]
Hey @1anshu-56 .  Please join our Discord server for further discussions and we'll be pleased if you come up with your designs and hover effects. 
You can simply raise the issue and add the prototype(Figma Snapshot) of the button there.

**Comment by vimalprogrammer** [comment]
@yashsehgal could you please assign me this issue...

**Comment by yashsehgal** [comment]
I have assigned you this issue, sorry I forgot and assigned this issue to myself 😅

**Comment by vimalprogrammer** [comment]
> I have assigned you this issue, sorry I forgot and assigned this issue to myself 😅

Yeah! That's bcoz, I'm a little bit confused...😅
