### ISSUE TITLE
cannot change the default font size of HTML elements in the CDN

### ISSUE THREAD

**Issue by WH0SUMIT** [DesignSystemsOSS/eccentrictouch#227]
**Describe the bug**
 If the user adds the CDN link to their file, then they cannot use the default HTML h1-h6 elements font size so this can be an issue.

**Expected behavior**
we can make new classes for font sizes so users can use the HTML default size as well as the eccentric touch classes. 

**Screenshots**
![image](https://user-images.githubusercontent.com/76095902/121589533-cb314700-ca54-11eb-991f-5165d679a110.png)

**Comment by ItsMeIshan** [comment]
Hey @WH0SUMIT @yashsehgal personally I don't think we need new classes for this work I guess the by default in the library the heading tags (h1,h2,h3,h4,h5,h6) are grouped with (et-h1, et-h2, et-h3, et-h4, et-h5, et-h6) so if we can ungroup them then users can use <h1> tag or other heading tags to use default styling. If you agree then I can work on this.

**Comment by yashsehgal** [comment]
Right @ItsMeIshan, We can work on this.

**Comment by ItsMeIshan** [comment]
sure! then getting a start on this! 🚀🚀

**Comment by yashsehgal** [comment]
Sure @ItsMeIshan 👍🏽 You can get started with this issue. I am assigning this to you :D

**Comment by WH0SUMIT** [comment]
as you can see I suggested that we can increase the font size, not the size of the h1-h6 element, so if we can implement these different font size classes in the code then we use these properties to increase the font size of the text in any elements in our code like h1-h6, span, div, p, etc.
