### ISSUE TITLE
[Component Feature]: Button Group component to be added

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#236]
**Is your feature request related to a problem? Please describe.**
We need to implement a button group feature as well in the library.
![image](https://user-images.githubusercontent.com/62352288/121675869-99aa9100-cad1-11eb-85a8-805adc3f9700.png)

**Describe the solution you'd like**
The code/feature implementation will look something like this

```html
<div class="btn-group">
  <button>Apple</button>
  <button>Samsung</button>
  <button>Sony</button>
</div>
```
The division will be holding all the buttons inserted in it.

**Useful Links**
- Read this article and you'll get an idea (https://www.w3schools.com/howto/howto_css_button_group.asp)

**Comment by Rishabhraghwendra18** [comment]
Hi. May I work on this issue ?

**Comment by Rishabhraghwendra18** [comment]
@yashsehgal do you have discord or slack server?

**Comment by yashsehgal** [comment]
Click [here](https://discord.gg/w7gYrmPWkF) to join

**Comment by Rishabhraghwendra18** [comment]
@yashsehgal may you guide me where to make my changes and how to check my changes ?
