### ISSUE TITLE
Adding Border 

### ISSUE THREAD

**Issue by WH0SUMIT** [DesignSystemsOSS/eccentrictouch#239]
**Describe the solution you'd like**
Adding border properties to add or remove an element’s borders. and users can choose from all borders or one at a time.

a) Border-top 
b) Border-bottom
c) Border-left 
d) Border-right
e) Border (set border on all sides of the element)
f)  Border-none (no borders)

**Additional context**
I want to contribute to this feature. I'm planning to add this border property to quickly style the border of an element and these properties are very useful for images, buttons, or any other element.

**Comment by Aditi-Singh16** [comment]
If no one's working on this issue, can you assign it to me?.

**Comment by yashsehgal** [comment]
@WH0SUMIT what's the status of other related issues? If you're working on them, let me assign this to @Aditi-Singh16

**Comment by harshita9621** [comment]
can you please assign this to me.

**Comment by Sejal2801** [comment]
Please assign it to me
