### ISSUE TITLE
Adding Border Radius

### ISSUE THREAD

**Issue by WH0SUMIT** [DesignSystemsOSS/eccentrictouch#240]
**Describe the solution you'd like**
Adding border radius property to an element to easily round its corners.

Border-radius ( for element to easily round its corners )
a) Border-round
b) Border-round-top
c) Border-round-bottom
d) Border-round-left 
e) Border-round-right
f)  Border-circle

**Additional context**
I want to contribute to this feature. I'm planning to add this border radius property to quickly style the border radius..

**Comment by RiyaGupta89** [comment]
Can I work on this issue or it is already assigned?

**Comment by WH0SUMIT** [comment]
@RiyaGupta89 I'm Working on this issue but You can create another one there are plenty of features and bugs so find out one and implement it.

**Comment by RiyaGupta89** [comment]
> @RiyaGupta89 I'm Working on this issue but You can create another one there are plenty of features and bugs so find out one and implement it.

Sure, np. Good luck!

**Comment by harshita9621** [comment]
can you please assign this to me.

**Comment by Sejal2801** [comment]
Please assign it to me
