### ISSUE TITLE
Adding Border Colors

### ISSUE THREAD

**Issue by atharvagadkari05** [DesignSystemsOSS/eccentrictouch#242]
This issue is related to add Border Color Property.

We would like to add the following border properties to our project: -
- Border-primary
- Border-invalid
- Border-warning
-  Border-valid
- Border-black
- Border-light

You can come up with the Figma file in the Discussion. No need to add all the border designs in the Figma file,
just give us an idea so that we'll have a greater idea of it.

**Comment by ItsMeIshan** [comment]
@WH0SUMIT @yashsehgal do you mean that we have to suggest a colour scheme for the different border properties? or please specify what do we mean by giving the idea here?

**Comment by yashsehgal** [comment]
> This issue is related to add Border Color Property.
> 
> We would like to add the following border properties to our project: -
> a) Border-primary
> b) Border-secondary
> c) Border-invalid
> d) Border-warning
> d) Border-valid
> e) Border-black
> f) Border-light
> 
> You can come up with the Figma file in the Discussion. No need to add all the border designs in the Figma file,
> just give us an idea so that we'll have a greater idea of it.

Hey, @ItsMeIshan This issue is basically listed for managing border properties.
All these border classes listed above are the colors we are using in the project (invalid, warning, valid)
Where (primary, secondary) will be based on default blue color.

And, (black, light) will be black border and white border, respectively.

Also, I think instead of using black, let's use `dark`

Do you want to add any point or change something @WH0SUMIT

**Comment by ItsMeIshan** [comment]
so it means that we have to give designs/ideas for designs for different border classes as mentioned above.
@yashsehgal

**Comment by ItsMeIshan** [comment]
@yashsehgal @WH0SUMIT are you talking about something like this 
https://www.figma.com/file/YZ1v2F4uYd2iqLYkQ7rHR7/border-colors?node-id=0%3A1

**Comment by WH0SUMIT** [comment]
Yes, @ItsMeIshan, all the border colors are those colors that are present in our project so try to implement the same colors and for the black one change it to the dark it will be more expressive.

**Comment by ItsMeIshan** [comment]
@yashsehgal will there be naming conventions for adding border colors too? like ```et-b-primary``` and so on...

**Comment by harshita9621** [comment]
can you please assign this to me.

**Comment by Sejal2801** [comment]
Please assign it to me
