### ISSUE TITLE
Adding Border Width

### ISSUE THREAD

**Issue by atharvagadkari05** [DesignSystemsOSS/eccentrictouch#247]
In this issue, we have to add border width.
Unit of these widths will be in `em`.

a) Border-1
b) Border-2
c) Border-3
d) Border-4
e) Border-5

Add accordingly and in case of any queries, you can participate in the discussions.

**Comment by ItsMeIshan** [comment]
hey, @atharvagadkari05 the value of em will be 1,2,3,4,5 according to that border classes?

**Comment by ItsMeIshan** [comment]
okay, then I can get started to work on this issue. @yashsehgal

**Comment by yashsehgal** [comment]
> hey, @atharvagadkari05 the value of em will be 1,2,3,4,5 according to that border classes?

what do you mean by `em` unit, because 1, 2, 3, 4, 5 `em`s are too large values for a border?

**Comment by ItsMeIshan** [comment]
> > hey, @atharvagadkari05 the value of em will be 1,2,3,4,5 according to that border classes?
> 
> what do you mean by `em` unit, because 1, 2, 3, 4, 5 `em`s are too large values for a border?

yup that's what i thought

**Comment by yashsehgal** [comment]
> > > hey, @atharvagadkari05 the value of em will be 1,2,3,4,5 according to that border classes?
> > 
> > 
> > what do you mean by `em` unit, because 1, 2, 3, 4, 5 `em`s are too large values for a border?
> 
> yup that's what i thought

Let's plan out the widths as well. Like, on using `et-border-1` the border-width actually will be `0.2em`, then `et-border-2` will be `0.4em` and so on. What do you think @ItsMeIshan @atharvagadkari05 @WH0SUMIT ??

**Comment by ItsMeIshan** [comment]
@yashsehgal that's awesome we can do this!

**Comment by yashsehgal** [comment]
+ one more thing

Try using the naming conventions as `et-bw-VALUE_OF_WIDTH`
where `bw` means border-width to keep the features easy to use.

**Comment by ItsMeIshan** [comment]
> * one more thing
> 
> Try using the naming conventions as `et-bw-VALUE_OF_WIDTH`
> where `bw` means border-width to keep the features easy to use.

it means we can go on like ```et-bw-1```, ```et-bw-2``` and so on @yashsehgal

**Comment by yashsehgal** [comment]
> > * one more thing
> > 
> > Try using the naming conventions as `et-bw-VALUE_OF_WIDTH`
> > where `bw` means border-width to keep the features easy to use.
> 
> it means we can go on like `et-bw-1`, `et-bw-2` and so on @yashsehgal

right! @ItsMeIshan 👍🏽

**Comment by yashsehgal** [comment]
I have assigned this issue to you, Go for it 🚀

**Comment by ItsMeIshan** [comment]
cool getting started with it!

**Comment by atharvagadkari05** [comment]
> > > > hey, @atharvagadkari05 the value of em will be 1,2,3,4,5 according to that border classes?
> > > 
> > > 
> > > what do you mean by `em` unit, because 1, 2, 3, 4, 5 `em`s are too large values for a border?
> > 
> > 
> > yup that's what i thought
> 
> Let's plan out the widths as well. Like, on using `et-border-1` the border-width actually will be `0.2em`, then `et-border-2` will be `0.4em` and so on. What do you think @ItsMeIshan @atharvagadkari05 @WH0SUMIT ??

@yashsehgal Sorry, I forgot to mention the exact no. but I think this looks great.

**Comment by atharvagadkari05** [comment]
@ItsMeIshan You can proceed with this and please remember the class naming convection specified by @yashsehgal.
