### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Amrutha1101** [DesignSystemsOSS/eccentrictouch#251]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
@yashsehgal  have you thought of adding favicon to the website? If yes I want to work on it under LGM-SOC'21.

**Comment by WH0SUMIT** [comment]
are you saying that you're going to create all the favicons and the designs of the favicons with your creativity???

**Comment by yashsehgal** [comment]
Hey @Amrutha1101 👋🏽 Hope you're doing great
By adding a favicon to the website, Are you talking about the docs website of this project?

**Comment by marizvi** [comment]
I would like to work on this issue, please assign this one to me..

**Comment by Amrutha1101** [comment]
@yashsehgal  yes adding favicon to the doc website to each of the components(button,headings..)
