### ISSUE TITLE
Can we add Copyright section in footer of part documentation page.

### ISSUE THREAD

**Issue by starrohan999** [DesignSystemsOSS/eccentrictouch#252]
**Is your feature request related to a problem? Please describe.**
There is no Copyright section in the footer of the page. 

**Screeshot**
![2021-06-12_LI](https://user-images.githubusercontent.com/71714344/121776373-190b9380-cbaa-11eb-8e3f-d88ba1f28e22.jpg)

**Additional context**
In this part would like to add.

**Comment by atharvagadkari05** [comment]
@starrohan999 Thanks for raising this issue, but I think we have to first implement the footer and then we can do other things like footer.

**Comment by starrohan999** [comment]
Ok sure @atharvagadkari05  Sir

**Comment by Sejal2801** [comment]
Please assign it to me
