### ISSUE TITLE
NPM Package proper configuration

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#253]
**Describe the bug**
The NPM Package for the eccentric touch has been published successfully and is downloadable as well. Currently, the file entry points are not working perfectly.

-  Here's the [NPM Published Package](https://www.npmjs.com/package/eccentrictouch)

**Comment by ItsMeIshan** [comment]
hey @yashsehgal how can I know if I did some changes for fixing the npm package and it works fine or not?

**Comment by yashsehgal** [comment]
🤔🤔 I think you have to publish the new package and test it out. Let's search for methods as well 😊

**Comment by ItsMeIshan** [comment]
I tried publishing the package but it gave some git errors and also for publishing I have to change the name of the package. still looking for some methods to try it out.
