### ISSUE TITLE
Image Shapes 

### ISSUE THREAD

**Issue by Ankita297** [DesignSystemsOSS/eccentrictouch#258]
In this issue we have different shapes of images 

1)  Circle image 
2)  Thumbnail image
3)  rounded corner image

or any other shape 

And in case of any query you can ask   here .

**Comment by WH0SUMIT** [comment]
hello, @Ankita297 can you please elaborate more on this issue, because we can implement circle images  & rounded corner images using border-radius properties.

**Comment by itsij** [comment]
I would to work on this issue. Plz assign this me @Ankita297

**Comment by Ankita297** [comment]
Yes we can implement them using border radius but like we can use  pre define class like if  we write circle-image class the image will be in circular shape . clear or not ?

**Comment by Ankita297** [comment]
@WH0SUMIT you have already one issue assigned ,So for now i am assigning this issue to @itsij  .

**Comment by Ankita297** [comment]
@itsij You may go ahead and if you face any query Please ask .

**Comment by yashsehgal** [comment]
Hey, @Ankita297 @itsij This property is already implemented in the border-property sprint. With that, we can do the same thing.

**Comment by yashsehgal** [comment]
@itsij You can get started with any other issue
