### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by utkarshgoel10** [DesignSystemsOSS/eccentrictouch#265]
Some minor changes could be made in the introduction paragraph, to make it sound much more appealing.

**Comment by utkarshgoel10** [comment]
Please assign this issue to me.

**Comment by yashsehgal** [comment]
Sure, @utkarshgoel10 👍🏽 You can get started with this one.

**Comment by nimishbhandari** [comment]
Can i work on this please?

**Comment by yashsehgal** [comment]
Hey 👋🏽 As of now, this issue has been assigned to @utkarshgoel10 
Feel free to look into other issues as well :D
