### ISSUE TITLE
Cards Alignment and Improvising

### ISSUE THREAD

**Issue by ashuydv** [DesignSystemsOSS/eccentrictouch#266]
So, in this issue, the cards is not looking nice, so how can we improvise it is, we can make image and align the cards in center,
and we can align all of them in center
![image](https://user-images.githubusercontent.com/67309431/121845243-c691ba80-cd02-11eb-8673-ad3a9804e391.png)

Do assign me this issue...

**Comment by ashuydv** [comment]
assign me this issue

**Comment by atharvagadkari05** [comment]
@ashuydv  Can you explain this issue further ??
Do you want the entire card container to be aligned at the center?

**Comment by Sejal2801** [comment]
Assign it to me

**Comment by ashuydv** [comment]
> @ashuydv Can you explain this issue further ??
> Do you want the entire card container to be aligned at the center?

What we can do is either add a heading, like Card Landscape, Card Portrait or we can align them in center with a single heading cards and please I commented first to assign me this issue  ....
