### ISSUE TITLE
Copy button to copy the code

### ISSUE THREAD

**Issue by RiyaGupta89** [DesignSystemsOSS/eccentrictouch#268]
![1](https://user-images.githubusercontent.com/72425181/121870977-34e57580-cd21-11eb-9486-20193c7bea25.png)
I can create a copy button in the href box so that if a user wants to copy the code, instead of first selecting and then copying, the user can simply click on that copy button to get the code copied then he/she will only have to paste the code wherever they want to.

**Comment by atharvagadkari05** [comment]
@RiyaGupta89 I'm assigning this issue to you.
Make sure you push your code on a separate branch.

**Comment by Amrutha1101** [comment]
Is anybody working on this issue(up for grab label found)?
