### ISSUE TITLE
[COMPONENT]: Carousel feature to be implemented

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#269]
**Is your feature request related to a problem? Please describe.**
We need to add a Carousel feature as well in the library.

**Describe the solution you'd like**
The component first needs to be designed and properly planned before implementation. You can get started with a basic design of the implementation you're planning and start coding the CSS part.

**Describe alternatives you've considered**
- Designs should be according to the theme we're following
- Keep things simple as possible, take your time to solve them.
- Follow the best coding practices

**Comment by WH0SUMIT** [comment]
@yashsehgal I want to contribute to this issue, I have a plan and good knowledge about this feature, and I know how we can implement this feature in our code.

please assign this issue to me.
