### ISSUE TITLE
Adding Hovering effects to buttons

### ISSUE THREAD

**Issue by puneetkaur2929** [DesignSystemsOSS/eccentrictouch#271]
Hey @yashsehgal @atharvagadkari05 

I wish to add different hovering effects to buttons.

kindly assign this issue to me under LGM SOC '21 .

**Comment by akankshashirure** [comment]
hey , i wish to add hovering  effects to buttons , can you please assign this to me.

**Comment by yashsehgal** [comment]
Hey @puneetkaur2929 👋🏽 
What kind of hovering effects you're planning to add

**Comment by puneetkaur2929** [comment]
@yashsehgal 
Following Hovering effects i will be applying on buttons:
1.Animation
2. Border change
3. color change
4. scale 
5. rotations
6. opacity changes
7. shadow hover effect
8. button grows on hovering.
Can explore more as well.

**Comment by harshita9621** [comment]
@yashsehgal , can you please assign this to me.

**Comment by puneetkaur2929** [comment]
@yashsehgal
 What's your thought regarding hovering effects?
