### ISSUE TITLE
Footer hover effect

### ISSUE THREAD

**Issue by Khushi-agarwal** [DesignSystemsOSS/eccentrictouch#272]
**Is your feature request related to a problem? Please describe.**
The footer icons do not have any hover effect on the website and also no colour. I would like to add both these things and also enhance it.
Please assign it to me under lgm-soc.

**Comment by atharvagadkari05** [comment]
@Khushi-agarwal All the website-related issues will be taken only on [Community](https://github.com/DesignSystemsOSS/community).
You may list this issue there.

**Comment by harshita9621** [comment]
@yashsehgal , can you please assign this to me.
