### ISSUE TITLE
Add complete another section of  CSS tables

### ISSUE THREAD

**Issue by codebuzzer01** [DesignSystemsOSS/eccentrictouch#274]
**Is your feature request related to a problem? Please describe.**
Usually tables form a major component of CSS which are used now and then. Without this feature, CSS library would seem incomplete.

**Describe the solution you'd like**
I would like to add an another complete section which will describe all CSS tables along with their snippets.

**Comment by codebuzzer01** [comment]
@yashsehgal  if u find it suitable, then assign me this under LGM-SOC'21.

**Comment by yashsehgal** [comment]
That's a great idea @codebuzzer01 👍🏽 We were also thinking about the same feature a few days before :)

I will assign this issue to you, also the flow to development of this issue will be
- First, you need to create a proper UI component design for tables
- Then after the design review, you can get started with the CSS implementation part

Good Luck! 🚀

**Comment by codebuzzer01** [comment]
Thanks @yashsehgal  :)

**Comment by codebuzzer01** [comment]
hey @yashsehgal 
check it out,  if its okay  I will continue with this .


https://user-images.githubusercontent.com/52864294/122094830-3a7ab280-ce2a-11eb-8356-edd160bbc2f1.mp4
