### ISSUE TITLE
Technologies used animation

### ISSUE THREAD

**Issue by Khushi-agarwal** [DesignSystemsOSS/eccentrictouch#275]
**Is your feature request related to a problem? Please describe.**
In the cards of the technologies used,I would like to add flip card animation.
Please assign it to me under lgmsoc.

**Comment by Khushi-agarwal** [comment]
@yashsehgal I would like to work not this.

**Comment by yashsehgal** [comment]
Could you please explain this issue and then maybe I can assign it to you

**Comment by Khushi-agarwal** [comment]
Im the technologies used section wherein html,css...are mentioned there I wang to add flip card animation so that on hovering over any card it would display it's name and on the front there would only be the picture/icon.
