### ISSUE TITLE
Adding a navbar component in library

### ISSUE THREAD

**Issue by PranavChauhan22** [DesignSystemsOSS/eccentrictouch#276]
**Is your feature request related to a problem? Please describe.**
I want to add a navbar component to the library as in some sites like bootstrap.

**Additional context**
 I have fully understood the library workflow and want to add an additional component to library.Please assign this issue to me under LGMSOC participant.

**Comment by yashsehgal** [comment]
Hey 👋🏽 @PranavChauhan22 
We have already created a navbar component but it's not working correctly. You as a contributor can design the component from scratch. I am assigning this issue to you 👍🏽
