### ISSUE TITLE
Implement color schemes as utility classes

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#303]
Create a set of color schemes as CSS utility classes for eccentric touch. The color details are given in the [core-properties page of Figma](https://www.figma.com/file/qvC8lBcNmnQevUDlTQROhG/?node-id=2%3A4). Do take a reference while working on this feature. 

**Feature progress**
- [x] Neutral colors
- [x] Base colors
- [x] State colors

**Comment by rishabhrathore055** [comment]
Should I Work On Yellow Color scheme

**Comment by rishabhrathore055** [comment]
![image](https://user-images.githubusercontent.com/77366500/135535558-1f650efd-0098-4387-bc5d-8aa6657fd122.png)

@yashsehgal

**Comment by yashsehgal** [comment]
@rishabhrathore055 Do try to stick with the gradient sequence. In this screenshot, the yellow color shades are looking very randomly generated.

**Comment by rishabhrathore055** [comment]
@yashsehgal  Sure I'll Update You

**Comment by rishabhrathore055** [comment]
@yashsehgal  Sure I'll Update very soon
