### ISSUE TITLE
[FEATURE] Create a CONTRIBUTING guidelines file

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#309]
### ⭐ Suggestion

We need to create a complete contributing guidelines file listing all the best contribution practices. The `CONTRIBUTING.md` file should have the following points.

- [ ] Welcome note section
- [ ] Branching system section
- [ ] How to write commit messages and PR summaries
- [ ] Basic SCSS related points

### 💻 Use Cases

This file will be helpful for the upcoming/new contributors who are going to start fresh with the project/development.

### ❌ Related Problems

Right now, we need to explain all of these things manually to everyone, this feature implementation will reduce the efforts and is a good resource to share with the contributors and people who are joining the team.

**Comment by yjaiswal05** [comment]
Hey, can i work on this issue?
