### ISSUE TITLE
[FEATURE] Create a README file for the project

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#310]
### ⭐ Suggestion

We need to work on a README file in order to make this project more understandable and usable. The things we need to add in the README docs

- [ ] Introduction/Project description
- [ ] Tech Stack (Languages and Libraries)
- [ ] Local environment setup details
- [ ] Guidelines section - with a link to redirect to the `CONTRIBUTING.md` file (for this refer to #309 )

### 💻 Use Cases

This file will be really helpful for the current/upcoming contributors. It will be easy to understand the project and local environment setup details and all other useful steps.

### ❌ Related Problems

Right now, we need to explain all of these things manually to everyone, this feature implementation will reduce the efforts and is a good resource to share with the contributors and people who are joining the team.

**Comment by vivekkj123** [comment]
Assign to me. I will work on Readme

**Comment by yashsehgal** [comment]
Thanks for working on this @snehafarkya
