### ISSUE TITLE
[FEATURE] Create elevations/shadow properties for components

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#311]
### ⭐ Suggestion

Implement shadow/elevation properties for components such as cards, images, buttons, and more. The shadow properties will be having the following variations

- [x] Default shadow
- [x] Light shadow
- [x] Medium shadow
- [x] High shadow

The following shadow variations are mentioned in the [Figma file](https://www.figma.com/file/qvC8lBcNmnQevUDlTQROhG/Eccentric-Touch-Design-System-by-The-DesignSystems?node-id=2%3A4)

**Screenshot**
![image](https://user-images.githubusercontent.com/62352288/135574627-ca369483-2948-4532-9ef0-33179d030be0.png)

### 💻 Use Cases

This feature will help frontend developers to add shadows to their components easily. 

### ❌ Related Problems

This is not directly related to any problem, It will help us to add more CSS properties to components

**Comment by yadavnarun** [comment]
Assign it to me

**Comment by MatteuSan** [comment]
Also, do we want users to customize the shadow color? or nah?

**Comment by yashsehgal** [comment]
Thanks for working on this feature @MatteuSan
