### ISSUE TITLE
Flex Properties Implementation using SCSS/CSS

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#53]
**Is your feature request related to a problem? Please describe.**
Eccentric Touch needs a flex-properties system. Classes with various flex properties (Ex: inline, block, flex, etc).

**Comment by nicoolel** [comment]
hello is this issue available for assignment?

**Comment by yashsehgal** [comment]
Hello @nicoolel 

Yes, This issue is open for all. Let me tell you what exactly we need to do.
So basically you need to make CSS/SCSS Class methods to implement all the display properties such as flex, inline-flex, block, etc. 

First, go through the codebase and understand the project as this will give you a brief idea about the project. The start writing code for this issue in the `src/lib/contents/contents.scss` or `src/lib/contents/contents.css`, whichever you are comfortable in. 

Also, Test your methods for this task in the `src/lib/contents/contentTest.htm` file.
Other than this if you have any doubt, you may ask :)

Good Luck!

Also, You should join the discord server, It'll be easy to communicate over there.
https://discord.gg/jdh2AcYm
