### ISSUE TITLE
[Testing] Testing CSS Class Methods

### ISSUE THREAD

**Issue by design-systems-oss** [DesignSystemsOSS/eccentrictouch#6]
Hello Fellow Testers, Looking for bugs? We have so many of them and we need you to resolve them.

**Describe the bug**
There are so many CSS Class methods which needs to be tested before production.

**How to get started?**
1. Go to `src/lib/...`
2. Select a feature folder for which you want to write tests for.
3. Write Test Methods for different scenarios in the respective HTML Module of that folder.
4. See for errors. If found any, Report a ne issue. Else, Write complete tests and submit with screenshots of the output.

**Expected Updates**
1. Test Modules with Clean Code.
2. Screenshots of the test case results.

**Comment by yashsehgal** [comment]
### Testing Needed
@Jaspreet099, There are more features that need to be tested. After Implementation of the latest theme, Test CSS Methods in their respective test modules. Hope you got my point.
