### ISSUE TITLE
JSDeliver - CDN Link is not working

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#99]
**Describe the bug**
After generating a CDN Link for the `eccentric.css` module, We are unable to fetch the CSS Data.

**Comment by yashsehgal** [comment]
https://cdn.jsdelivr.net/gh/DesignSystemsOSS/eccentrictouch@v2.0/src/lib/eccentric.css

This is the test CDN link we are trying to use

**Comment by Rahma-AlWadhahi** [comment]
> https://cdn.jsdelivr.net/gh/DesignSystemsOSS/eccentrictouch@v2.0/src/lib/eccentric.css
> 
> This is the test CDN link we are trying to use

I’m not sure why, but when I removed `@v2.0` from the link. I could see the css data.

**Comment by yashsehgal** [comment]
Wait, That's great @Rahma-AlWadhahi.
But, How it is possible 😆

**Comment by Rahma-AlWadhahi** [comment]
Maybe when the CDN was created, it didn't have a specified version which led to this mistake 🤔
I'm just guessing because I haven't done it before 😅

**Comment by yashsehgal** [comment]
Yeah, That's not an issue. But what is happening that it's showing the code from the master branch, but the code is different on all the branches. 🤔

**Comment by yashsehgal** [comment]
Yeah But that's alright, you did a nice job. It was a very silly bug 🤓 👍🏽
